apiVersion: apps/v1
kind: Deployment
metadata:
  name: discord-bot
  namespace: chris-discord
  labels:
    app: discord-bot
spec:
  replicas: 2
  selector:
    matchLabels:
      app: discord-bot
  template:
    metadata:
      labels:
        app: discord-bot
    spec:
      containers:
        - name: discord-bot
          image: docker.io/christophertyoung/discord_bot:latest
          ports:
            - containerPort: 8000
          env:
            - name: VITE_DISCORD_CLIENT_ID
              valueFrom:
                secretKeyRef:
                  name: discord-bot-secret
                  key: VITE_DISCORD_CLIENT_ID
            - name: VITE_DISCORD_CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: discord-bot-secret
                  key: VITE_DISCORD_CLIENT_SECRET
            - name: VITE_DISCORD_BOT_URL
              valueFrom:
                secretKeyRef:
                  name: discord-bot-secret
                  key: VITE_DISCORD_BOT_URL
            - name: VITE_DISCORD_BOT_TOKEN
              valueFrom:
                secretKeyRef:
                  name: discord-bot-token
                  key: VITE_DISCORD_BOT_TOKEN
            - name: DISCORD_SESSION_SECRET
              valueFrom:
                secretKeyRef:
                  name: discord-bot-secret
                  key: DISCORD_SESSION_SECRET
            - name: FRONTEND_ORIGINS
              value: "https://discord-bot-controller.duckdns.org"
            - name: DISCORD_REDIRECT_URI
              value: "https://discord-bot-controller.duckdns.org/api/auth/callback"
            - name: DISCORD_SESSION_SAMESITE
              value: "none"
            - name: DISCORD_SESSION_HTTPS_ONLY
              value: "true"
            - name: DB_CONNECTION_STRING
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: DB_CONNECTION_STRING

          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"

---
apiVersion: v1
kind: Service
metadata:
  name: discord-bot-svc
  namespace: chris-discord
  labels:
    app: discord-bot
spec:
  type: ClusterIP
  selector:
    app: discord-bot
  ports:
    - port: 8000
      targetPort: 8000
      protocol: TCP
      name: http
