apiVersion: apps/v1
kind: Deployment
metadata:
  name: discord-bot
  namespace: chris-discord
  labels:
    app: discord-bot
spec:
  replicas: 2
  selector:
    matchLabels:
      app: discord-bot
  template:
    metadata:
      labels:
        app: discord-bot
    spec:
      containers:
        - name: discord-bot
          image: docker.io/christophertyoung/discord_bot:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8000
          env:
            - name: VITE_DISCORD_CLIENT_ID
              valueFrom:
                secretKeyRef:
                  name: discord-bot-secret
                  key: DISCORD_CLIENT_ID
            - name: VITE_DISCORD_CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: discord-bot-secret
                  key: DISCORD_CLIENT_SECRET
            - name: VITE_DISCORD_BOT_URL
              valueFrom:
                secretKeyRef:
                  name: discord-bot-secret
                  key: DISCORD_BOT_URL

          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"

---
apiVersion: v1
kind: Service
metadata:
  name: discord-bot-svc
  namespace: chris-discord
  labels:
    app: discord-bot
spec:
  type: ClusterIP
  selector:
    app: discord-bot
  ports:
    - port: 8000
      targetPort: 8000
      protocol: TCP
      name: http
