import os
import discord
from discord.ext import commands
import asyncio
import httpx
from typing import Optional, List, Dict, Any
from services.llm_service import llm_service
from services.llm_tools import register_tools, tool_change_bot_nickname, tool_send_message


class BotService:
    def __init__(self):
        self.bot_token = os.environ.get("DISCORD_BOT_TOKEN") or os.environ.get("VITE_DISCORD_BOT_TOKEN")
        self.message_service = None
        self.settings_service = None
        self.offense_service = None

        intents = discord.Intents.default()
        intents.guilds = True
        intents.guild_messages = True
        intents.dm_messages = True
        intents.message_content = True

        self.bot = commands.Bot(command_prefix="!", intents=intents)
        self.bot_task: Optional[asyncio.Task] = None

        self._register_events()

        register_tools(llm_service, self)

    def message_is_mention(self, message):
        bot_user = self.bot.user
        if bot_user:
            if bot_user in message.mentions:
                return True
            else:
                content = message.content or ""
                if f"<@{bot_user.id}>" in content or f"<@!{bot_user.id}>" in content:
                    return True

        return False

    async def announce_nickname_change(self, guild_id: str, old_nickname: str, new_nickname: str) -> None:
        if not self.is_ready():
            print("DEBUG: Bot not ready; skipping nickname announcement")
            return

        nickname_result = await tool_change_bot_nickname(self, guild_id, new_nickname)

        if not nickname_result.get("success"):
            print(f"WARNING: Failed to change bot nickname: {nickname_result.get('error')}")
            return

        personality = await self._get_personality(guild_id)

        system_prompt = llm_service.build_system_prompt(personality=personality, use_tools=False)

        user_prompt = (
            f"You just changed your nickname to '{new_nickname}' in the Discord server. "
            f"Generate a short, friendly message announcing your new name. "
            f"Be creative but concise (1-2 sentences max). "
            f"Example style: 'Hello everyone! I am now {new_nickname} 😊'"
        )

        announcement = await llm_service.generate_response(
            user_message=user_prompt,
            system_prompt=system_prompt,
            use_tools=False,
        )

        if not announcement:
            print("DEBUG: No announcement generated by LLM")
            return

        guild = self.get_guild_by_id(int(guild_id))
        if not guild:
            print(f"WARNING: Guild {guild_id} not found when announcing nickname change")
            return

        target_channel_id = None
        for channel in guild.text_channels:
            if channel.permissions_for(guild.me).send_messages:
                target_channel_id = str(channel.id)
                break

        if not target_channel_id:
            print(f"WARNING: No suitable channel to send nickname announcement in guild {guild_id}")
            return

        send_result = await tool_send_message(self, guild_id, target_channel_id, announcement)
        if not send_result.get("success"):
            print(f"WARNING: Failed to send nickname announcement: {send_result.get('error')}")
        else:
            print(f"DEBUG: Sent nickname announcement in guild {guild_id}")

    def _register_events(self):
        @self.bot.event
        async def on_ready():
            print(f"Bot logged in as {self.bot.user}")
            print(f"Bot is in {len(self.bot.guilds)} guilds:")
            for guild in self.bot.guilds:
                print(f"  - {guild.name} (ID: {guild.id})")

        @self.bot.event
        async def on_guild_join(guild: discord.Guild):
            print(f"Bot joined guild: {guild.name} (ID: {guild.id})")

        @self.bot.event
        async def on_guild_remove(guild: discord.Guild):
            print(f"Bot removed from guild: {guild.name} (ID: {guild.id})")

        @self.bot.event
        async def on_error(event, *args, **kwargs):
            print(f"ERROR in event {event}:", args, kwargs)
            import traceback

            traceback.print_exc()

        @self.bot.event
        async def on_message(message: discord.Message):
            if message.author == self.bot.user:
                return

            print(f"DEBUG: Message received from {message.author.name} in {type(message.channel).__name__}")

            if isinstance(message.channel, discord.TextChannel):
                guild = message.guild
                guild_id_str = str(guild.id) if guild else None

                # Only check user messages (not bot messages, and not empty messages)
                if guild_id_str and self.settings_service and self.offense_service:
                    # Skip if message is from bot or if both content and attachments are empty
                    if message.author != self.bot.user and (message.content or message.attachments):
                        await self._check_offensive_content(message, guild_id_str)

                if self.message_is_mention(message):
                    await self._handle_server_message(message)

            elif isinstance(message.channel, discord.DMChannel):
                await self._handle_dm(message)

            await self.bot.process_commands(message)

    async def _build_conversation_history(
        self, user_id: str = None, guild_id: str = None, channel_id: str = None, limit: int = 10
    ) -> List[Dict[str, str]]:
        if not self.message_service:
            return []

        if user_id and not guild_id:
            messages = await self.message_service.get_history(limit=limit * 2, guild_id="DM", channel_id=channel_id)
        elif guild_id and channel_id:
            messages = await self.message_service.get_history(limit=limit * 2, guild_id=guild_id, channel_id=channel_id)
        else:
            messages = await self.message_service.get_history(limit=limit * 2)

        conversation = []
        for msg in messages[-limit:]:
            msg_type = msg.get("type")
            content = msg.get("content", "")
            username = msg.get("username", "Unknown")

            if msg_type == "sent":
                conversation.append({"role": "assistant", "content": content})
            elif msg_type in ["dm", "received"]:
                conversation.append({"role": "user", "content": f"{username}: {content}"})

        filtered_conversation = []
        for msg in conversation:
            if not filtered_conversation or filtered_conversation[-1]["role"] != msg["role"]:
                filtered_conversation.append(msg)
            else:
                filtered_conversation[-1]["content"] += "\n" + msg["content"]

        return filtered_conversation

    async def _get_personality(self, guild_id: Optional[str]) -> Optional[str]:
        if not guild_id or guild_id == "DM" or not self.settings_service:
            return None

        try:
            settings = await self.settings_service.get_settings(guild_id)
            if settings and settings.get("settings"):
                s = settings["settings"]
                if isinstance(s, dict):
                    bot_settings = s.get("bot_settings")
                    if bot_settings and isinstance(bot_settings, dict):
                        return bot_settings.get("personality")
                    return s.get("personality")
        except Exception as e:
            print(f"ERROR fetching personality settings: {e}")
            return None

        return None

    async def _check_offensive_content(self, message: discord.Message, guild_id: str) -> None:
        """Check message for violations and let LLM decide whether to remove it"""
        settings = await self.settings_service.get_settings(guild_id)
        if not settings or not settings.get("settings"):
            return

        maturity_prefs = settings["settings"].get("content_maturity_preferences", {})
        allowed_score = maturity_prefs.get("allowed_maturity_score", 10)
        banned_content = maturity_prefs.get("banned_content", [])

        # Build context for LLM
        banned_list = ", ".join(banned_content) if banned_content else "none"

        # Include attachment info
        attachment_info = ""
        if message.attachments:
            attachment_types = [att.content_type or "unknown" for att in message.attachments]
            attachment_info = f"\nAttachments: {', '.join(attachment_types)}"

        message_text = message.content if message.content else "[No text content]"

        prompt = f"""Analyze this Discord message for content maturity violations.

Server Rules:
- Allowed maturity score: 0-{allowed_score} (0=G-rated family-friendly, 10=extreme adult content)
- Banned content keywords: {banned_list}

Message from user <@{message.author.id}>:
"{message_text}"{attachment_info}

IMPORTANT: Only flag messages that CLEARLY violate the rules. Normal conversation, greetings, questions, and friendly chat are acceptable and should NOT be removed.

Evaluate the message:
1. Rate its maturity level from 0-10
2. Check if it contains any banned keywords (exact matches only)
3. Determine if it CLEARLY violates the rules (score EXCEEDS {allowed_score})

ONLY call the remove_offensive_message tool if:
- The message contains an EXACT banned keyword from the list, OR
- The maturity score is GREATER THAN {allowed_score} (not equal to, but greater than)

If the message is acceptable or borderline, DO NOT remove it. Simply respond with "Message is acceptable."

Required parameters for the tool (only if removing):
- guild_id: {guild_id}
- channel_id: {message.channel.id}
- message_id: {message.id}
- user_id: {message.author.id}
- message_content: {message.content}
- offensive_score: your 0-10 rating

If the message is acceptable, simply respond with "Message is acceptable" and do not call any tools."""

        await llm_service.generate_response(user_message=prompt, conversation_history=[], use_tools=True)

    async def _handle_dm(self, message: discord.Message):
        print(f"DEBUG: DM detected! Message service connected: {self.message_service is not None}")

        if self.message_service:
            await self.message_service.add_to_history(
                message_type="dm",
                content=message.content,
                user_id=str(message.author.id),
                username=message.author.name,
                guild_id="DM",
                channel_id=str(message.channel.id),
                message_id=str(message.id),
            )
            print(f"DEBUG: DM added to history from {message.author.name}: {message.content}")
        else:
            print("WARNING: Message service not connected!")

        print(f"DM received from {message.author.name}: {message.content}")

        conversation_history = await self._build_conversation_history(
            user_id=str(message.author.id), channel_id=str(message.channel.id), limit=10
        )
        print(f"DEBUG: Built conversation history with {len(conversation_history)} messages for DM")

        print(f"DEBUG: Generating LLM response for DM from {message.author.name}")

        llm_response = await llm_service.generate_discord_response(
            user_message=message.content,
            username=message.author.name,
            is_dm=True,
            conversation_history=conversation_history,
            personality=None,
        )

        if llm_response:
            print(f"DEBUG: LLM response generated: {llm_response[:100]}...")
            await message.channel.send(llm_response)
            print(f"DEBUG: LLM response sent to {message.author.name}")

            if self.message_service:
                await self.message_service.add_to_history(
                    message_type="sent",
                    content=llm_response,
                    user_id=str(self.bot.user.id),
                    username=self.bot.user.name,
                    guild_id="DM",
                    channel_id=str(message.channel.id),
                )
        else:
            print("ERROR: Failed to generate LLM response")
            await message.channel.send("Sorry, I'm having trouble generating a response right now.")

    async def _handle_server_message(self, message: discord.Message):
        print(f"DEBUG: Server message detected! Message service connected: {self.message_service is not None}")

        guild = message.guild
        guild_id_str = str(guild.id) if guild else None

        if self.message_service:
            await self.message_service.add_to_history(
                message_type="received",
                content=message.content,
                user_id=str(message.author.id),
                username=message.author.name,
                guild_id=guild_id_str,
                guild_name=guild.name if guild else None,
                channel_id=str(message.channel.id),
                channel_name=message.channel.name,
                message_id=str(message.id),
            )
            print(
                f"DEBUG: Server message added to history from {message.author.name} in #{message.channel.name}: {message.content}"
            )
        else:
            print("WARNING: Message service not connected!")

        conversation_history = await self._build_conversation_history(
            guild_id=guild_id_str, channel_id=str(message.channel.id), limit=10
        )
        print(f"DEBUG: Built conversation history with {len(conversation_history)} messages for server")

        personality = await self._get_personality(guild_id_str)
        if personality:
            print(f"DEBUG: Using personality setting for guild {guild_id_str}: {personality[:50]}...")

        print(f"DEBUG: Generating LLM response for server message from {message.author.name}")

        llm_response = await llm_service.generate_discord_response(
            user_message=message.content,
            username=message.author.name,
            is_dm=False,
            channel_name=message.channel.name,
            guild_id=guild_id_str,
            guild_name=guild.name if guild else None,
            conversation_history=conversation_history,
            use_tools=True,
            personality=personality,
        )

        if llm_response:
            print(f"DEBUG: LLM response generated: {llm_response[:100]}...")
            sent_message = await message.channel.send(llm_response)
            print(f"DEBUG: LLM response sent to #{message.channel.name}")

            if self.message_service:
                guild = message.guild
                await self.message_service.add_to_history(
                    message_type="sent",
                    content=llm_response,
                    user_id=str(self.bot.user.id),
                    username=self.bot.user.name,
                    guild_id=str(guild.id) if guild else None,
                    guild_name=guild.name if guild else None,
                    channel_id=str(message.channel.id),
                    channel_name=message.channel.name,
                    message_id=str(sent_message.id),
                )
        else:
            print("ERROR: Failed to generate LLM response")
            await message.channel.send("Sorry, I'm having trouble generating a response right now.")

    async def start(self):
        print(f"DEBUG: DISCORD_BOT_TOKEN configured: {bool(self.bot_token)}")
        if self.bot_token:
            print(f"DEBUG: Token preview: {self.bot_token[:20]}...")
            print(f"DEBUG: Starting Discord bot...")
            self.bot_task = asyncio.create_task(self.bot.start(self.bot_token))
            print(f"DEBUG: Bot task created successfully")

            def task_done_callback(task):
                if task.exception():
                    print(f"ERROR: Bot task failed with exception: {task.exception()}")
                    import traceback

                    traceback.print_exception(type(task.exception()), task.exception(), task.exception().__traceback__)

                self.bot_task.add_done_callback(task_done_callback)

        else:
            print("Warning: DISCORD_BOT_TOKEN not set, bot will not start")

    async def stop(self):
        if self.bot_task and not self.bot_task.done():
            await self.bot.close()
            self.bot_task.cancel()

    def is_ready(self) -> bool:
        return self.bot.is_ready()

    def get_guilds(self) -> List[Dict[str, str]]:
        if not self.is_ready():
            return []

        return [
            {"id": str(guild.id), "name": guild.name, "icon": guild.icon.url if guild.icon else None}
            for guild in self.bot.guilds
        ]

    def get_guild_by_id(self, guild_id: int):
        return self.bot.get_guild(guild_id)

    def get_channel_by_id(self, channel_id: int):
        return self.bot.get_channel(channel_id)

    async def send_message(self, channel_id: int, message: str, user_id: str = None, username: str = None) -> bool:
        channel = self.get_channel_by_id(channel_id)
        if not channel:
            raise ValueError("Channel not found")

        if not isinstance(channel, discord.TextChannel):
            raise ValueError("Channel is not a text channel")

        sent_message = await channel.send(message)

        if self.message_service:
            guild = channel.guild
            await self.message_service.add_to_history(
                message_type="sent",
                content=message,
                user_id=user_id,
                username=username,
                guild_id=str(guild.id) if guild else None,
                guild_name=guild.name if guild else None,
                channel_id=str(channel.id),
                channel_name=channel.name,
                message_id=str(sent_message.id),
            )

        return True


bot_service = BotService()
