name: Build and push Docker images

on:
  push:
    branches: [ main ]
  workflow_dispatch: {}

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: christophertyoung
          password: ${{ secrets.DOCKERHUB_PASS }}

      - name: Get latest Docker Hub tag
        id: previous_version
        run: |
          TAGS_JSON=$(curl -s "https://hub.docker.com/v2/repositories/christophertyoung/discord_bot_controller/tags/?page_size=100")
          
          echo "$TAGS_JSON"
          LATEST_TAG=$(echo "$TAGS_JSON" | jq -r '.results[].name' | grep -E '^v[0-9]+$' | sort -V | tail -n 1)
          
          if [ -z "$LATEST_TAG" ]; then
            echo "version=0" >> $GITHUB_OUTPUT
            echo "No previous version found, starting at v0"
          else
            echo "version=${LATEST_TAG#v}" >> $GITHUB_OUTPUT
            echo "Latest Docker Hub version: $LATEST_TAG"
          fi

      - name: Increment version
        id: increment_version
        run: |
          VERSION=${{ steps.previous_version.outputs.version }}
          PATCH=$((VERSION + 1))
          NEW_VERSION="v${PATCH}"
          echo "new_version=$NEW_VERSION" >> $GITHUB_OUTPUT
          echo "New version: $NEW_VERSION"

      - name: Build and push discord_bot image
        uses: docker/build-push-action@v4
        with:
          context: ./discord_bot
          file: ./discord_bot/Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            docker.io/christophertyoung/discord_bot:latest
            docker.io/christophertyoung/discord_bot:${{ steps.increment_version.outputs.new_version }}

      - name: Build and push web_controller image
        uses: docker/build-push-action@v4
        with:
          context: ./web_controller
          file: ./web_controller/Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            docker.io/${{ secrets.DOCKERHUB_USERNAME }}/discord_bot_controller:latest
            docker.io/${{ secrets.DOCKERHUB_USERNAME }}/discord_bot_controller:${{ steps.increment_version.outputs.new_version }}
